# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chef Kit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for Chef Kit
  pod 'FlexLayout'
  pod 'PinLayout'
  pod 'lottie-ios'
  pod 'Alamofire'
  pod 'Moya', '~> 12.0'
  pod 'RxSwift', '~> 5.0.1'
  pod 'RxCocoa', '~> 5.0.1'
  pod 'ObjectMapper', '~> 3.5'

  target 'Chef KitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Chef KitUITests' do
    # Pods for testing
  end

end
